import { HeatingConfig } from '../interfaces/heating.interface';

const defaultTemperatureSettings = {
	HYSTERESIS: 0.5,
	TEMP_LOW_1: 15,
	TEMP_LOW_2: 18,
	TEMP_HIGH: 25,
	TEMP_FREEZE_LIMIT: 5,
	TEMP_OVERHEAT_LIMIT: 35,
};

const defaultPIDSettings = {
	Kp: 2.0,     // Коэффициент пропорциональности
	Ki: 0.5,     // Коэффициент интегральной составляющей
	Kd: 2.0,     // Коэффициент дифференциальной составляющей
	outputMin: 0,    // Минимальное значение выхода
	outputMax: 100,  // Максимальное значение выхода (0-100%)
	integral: 0,     // Интегральная составляющая
	prevError: 0,    // Предыдущая ошибка
};

export const heatingConfigs: Record<string, HeatingConfig> = {
	ШУК1: {
		deviceName: 'ШУК1',
		relayModule: 'wb-mr6cu_86',
		analogModule: 'wb-mao4_168',
		tempModule: 'wb-msw-v4_24',
		deviceRealName: 'Управление отоплением 1',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_86/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_168/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_19/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК10: {
		deviceName: 'ШУК10',
		relayModule: 'wb-mr6cu_28',
		analogModule: 'wb-mao4_208',
		tempModule: 'wb-msw-v4_31',
		deviceRealName: 'Управление отоплением 10',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_28/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_208/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_31/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК11: {
		deviceName: 'ШУК11',
		relayModule: 'wb-mr6cu_111',
		analogModule: 'wb-mao4_117',
		tempModule: 'wb-msw-v4_36',
		deviceRealName: 'Управление отоплением 11',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_111/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_117/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_36/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК12: {
		deviceName: 'ШУК12',
		relayModule: 'wb-mr6cu_93',
		analogModule: 'wb-mao4_184',
		tempModule: 'wb-msw-v4_90',
		deviceRealName: 'Управление отоплением 12',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_93/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_184/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_90/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК13: {
		deviceName: 'ШУК13',
		relayModule: 'wb-mr6cu_95',
		analogModule: 'wb-mao4_119',
		tempModule: 'wb-msw-v4_90',
		deviceRealName: 'Управление отоплением 13',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_95/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_119/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_90/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК14: {
		deviceName: 'ШУК14',
		relayModule: 'wb-mr6cu_128',
		analogModule: 'wb-mao4_203',
		tempModule: 'wb-msw-v4_22',
		deviceRealName: 'Управление отоплением 14',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_128/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_203/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_22/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК15: {
		deviceName: 'ШУК15',
		relayModule: 'wb-mr6cu_71',
		analogModule: 'wb-mao4_216',
		tempModule: 'wb-msw-v4_15',
		deviceRealName: 'Управление отоплением 15',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_71/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_216/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_15/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК16: {
		deviceName: 'ШУК16',
		relayModule: 'wb-mr6cu_26',
		analogModule: 'wb-mao4_197',
		tempModule: 'wb-msw-v4_70',
		deviceRealName: 'Управление отоплением 16',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_26/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_197/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_70/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК17: {
		deviceName: 'ШУК17',
		relayModule: 'wb-mr6cu_17',
		analogModule: 'wb-mao4_191',
		tempModule: 'wb-msw-v4_85',
		deviceRealName: 'Управление отоплением 17',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_17/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_191/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_85/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК18: {
		deviceName: 'ШУК18',
		relayModule: 'wb-mr6cu_139',
		analogModule: 'wb-mao4_206',
		tempModule: 'wb-msw-v4_80',
		deviceRealName: 'Управление отоплением 18',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_139/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_206/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_80/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК19: {
		deviceName: 'ШУК19',
		relayModule: 'wb-mr6cu_38',
		analogModule: 'wb-mao4_199',
		tempModule: 'wb-msw-v4_92',
		deviceRealName: 'Управление отоплением 19',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_38/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_199/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_92/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК2: {
		deviceName: 'ШУК2',
		relayModule: 'wb-mr6cu_51',
		analogModule: 'wb-mao4_142',
		tempModule: 'wb-msw-v4_105',
		deviceRealName: 'Управление отоплением 2',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_51/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_142/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_105/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК20: {
		deviceName: 'ШУК20',
		relayModule: 'wb-mr6cu_81',
		analogModule: 'wb-mao4_121',
		tempModule: 'wb-msw-v4_35',
		deviceRealName: 'Управление отоплением 20',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_81/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_121/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_35/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК3: {
		deviceName: 'ШУК3',
		relayModule: 'wb-mr6cu_98',
		analogModule: 'wb-mao4_211',
		tempModule: 'wb-msw-v4_13',
		deviceRealName: 'Управление отоплением 3',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_98/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_211/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_13/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК4: {
		deviceName: 'ШУК3',
		relayModule: 'wb-mr6cu_96',
		analogModule: 'wb-mao4_125',
		tempModule: 'wb-msw-v4_229',
		deviceRealName: 'Управление отоплением 3',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_96/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_125/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_229/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК5: {
		deviceName: 'ШУК5',
		relayModule: 'wb-mr6cu_127',
		analogModule: 'wb-mao4_210',
		tempModule: 'wb-msw-v4_33',
		deviceRealName: 'Управление отоплением 5',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_127/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_210/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_33/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК6: {
		deviceName: 'ШУК6',
		relayModule: 'wb-mr6cu_105',
		analogModule: 'wb-mao4_122',
		tempModule: 'wb-msw-v4_74',
		deviceRealName: 'Управление отоплением 6',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_105/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_122/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_74/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК7: {
		deviceName: 'ШУК7',
		relayModule: 'wb-mr6cu_21',
		analogModule: 'wb-mao4_186',
		tempModule: 'wb-msw-v4_74',
		deviceRealName: 'Управление отоплением 7',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_21/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_186/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_74/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК8: {
		deviceName: 'ШУК8',
		relayModule: 'wb-mr6cu_83',
		analogModule: 'wb-mao4_193',
		tempModule: 'wb-msw-v4_171',
		deviceRealName: 'Управление отоплением 8',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_83/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_193/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_171/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
	ШУК9: {
		deviceName: 'ШУК9',
		relayModule: 'wb-mr6cu_58',
		analogModule: 'wb-mao4_202',
		tempModule: 'wb-msw-v4_31',
		deviceRealName: 'Управление отоплением 9',
		topics: {
			VALVE_RELAY: '/devices/wb-mr6cu_58/controls/K1',
			FAN_DIMMER: '/devices/wb-mao4_202/controls/Channel 1 Dimming Level',
			TEMPERATURE_SENSOR: '/devices/wb-msw-v4_31/controls/Temperature',
		},
		temperatureSettings: defaultTemperatureSettings,
		pidSettings: { ...defaultPIDSettings },
		broker: 'heating',
	},
};
